app:
  image: deseretbook/kamas
  ports:
    - '3000:3000'
  links:
    - postgres:db
  environment:
    POSTGRES_HOST: db
    POSTGRES_DB: deseretbook_spree
    POSTGRES_USER: deseretbook_spree

postgres:
  image: postgres:latest
  ports:
    - '5432:5432'
  volumes:
    - /docker/postgres/data:/var/lib/postgresql/data
  environment:
    POSTGRES_DB: deseretbook_spree
    POSTGRES_USER: deseretbook_spree
